type User @table {
  email: String! @unique
  passwordHash: String!
  role: String!
  createdAt: Timestamp!
  firstName: String
  lastName: String
  approved: Boolean
}

type TeacherProfile @table {
  user: User!
  bio: String
  subjects: [String]
  officeLocation: String
}

type AvailabilitySlot @table {
  teacherProfile: TeacherProfile!
  startTime: Timestamp!
  endTime: Timestamp!
  isBooked: Boolean!
}

type Appointment @table {
  student: User!
  teacherProfile: TeacherProfile!
  availabilitySlot: AvailabilitySlot!
  appointmentTime: Timestamp!
  status: String!
  createdAt: Timestamp!
  notes: String
  rejectionReason: String
}

type Message @table {
  sender: User!
  receiver: User!
  content: String!
  sentAt: Timestamp!
  read: Boolean!
}